cask_args appdir: "/Applications"
#tap "homebrew/cask"

brew "gibo"
brew "git"
brew "aicommits"
brew "jq"
brew "nvm"
brew "peco"
brew "tree"
brew "vim"
brew "wget"
brew "zsh"
brew "zsh-completions"
brew "asdf"
brew "gpg"
brew "gh"
brew "webp"
brew "tmux"
brew "ollama"

cask "google-chrome"
cask "firefox"
cask "arc"

cask "raycast"
cask "iterm2"
#cask "warp"
cask "intellij-idea"

cask "notion"
cask "figma"

cask "slack"
cask "thunderbird"
cask "readdle-spark"
cask "zoom"
cask "bathyscaphe"

cask "google-japanese-ime"
brew "docker"
cask "docker"

cask "dropbox"
cask "google-drive"
#cask "amazon-photos"

cask "Kobo"
cask "kindle"

cask "cyberduck"
#cask "chatgpt"

